### ISSUE TITLE
Add -y option to e2fsck

### ISSUE THREAD

**Issue by ENM185** [SOL-Space-Operating-Linux/meta-sol#19]

**Comment by pdlloyd** [comment]
I couldn't find where `e2fsck` was used in the build but from what I know about the tool, this could be a useful way to automate checking the filesystem during runtime and fixing certain classes of errors automatically. However, from [the `man` page](https://linux.die.net/man/8/e2fsck):

> -p
>    Automatically repair ("preen") the file system. This option will cause e2fsck to automatically fix any filesystem problems that can be safely fixed without human intervention. If e2fsck discovers a problem which may require the system administrator to take additional corrective action, e2fsck will print a description of the problem and then exit with the value 4 logically or'ed into the exit code. (See the EXIT CODE section.) This option is normally used by the system's boot scripts. It may not be specified at the same time as the -n or -y options. 
> 
> -y
>    Assume an answer of 'yes' to all questions; allows e2fsck to be used non-interactively. This option may not be specified at the same time as the -n or -p options.

So it looks like whatever script calls e2fsck should just specify the `-p` option. Is the idea to call this as a `cron` job on some interval?

**Comment by ENM185** [comment]
Thanks for pointing out that they can't be used simultaneously @pdlloyd. I think I answered this live a couple weeks ago, but we'll just use `-y` since we'd want a usable file system over all else.
