### ISSUE TITLE
Add a CUDA package list

### ISSUE THREAD

**Issue by Atomicchipmonk** [SOL-Space-Operating-Linux/meta-sol#5]
Should provide CUDA needs to run nvidia test applications

**Comment by floyd501** [comment]
@Atomicchipmonk I'm getting compilation errors when adding `cuda-samples` to packagegroup-devtools.  It's complaining about `omp.h` (OpenMP), but the `-fopenmp` compiler flag is set, which I think is all that's needed, so I'm not really sure where to poke (sol, tegra, or even poky/oe).  Could this have anything to do with the version of gcc we're using?
